print("GEROBAK FRIED CHICKEN")
print("--------------------------")
print("Jenis Mobil      |   Jenis    Harga")
print("Toyota Avanza    |    Rp.2500")
print("Toyota Avanza    |    Rp.2500")
print("Toyota Avanza    |    Rp.2500")
print("Toyota Avanza    |    Rp.2500")
print("Toyota Avanza    |    Rp.2500")
print("2    Paha    Rp.2000")
print("3    Sayap   Rp.1500")
print("4    Keluar  Rp.000")
print("--------------------------")